config/routes.rb
Rails.application.routes.draw do

  get    'signup'  =>  'users#new'
  get    'login'   =>  'sessions#new'
  post   'login'   =>  'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users

  get 'users/new'
  resources :quizzes do 
    resources :questions
  end 

  resources :questions do
    resources :answers, only: [:create, :update]
  end
  
  resources :categories

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :quizzes

  validates :title, presence: {message: "Must provide a title!"}, uniqueness: {scope: :title}

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def new
    @category = Category.new
  end

  def create
    # render text: params
    @category = Category.new category_params
    @category.save
    redirect_to categories_path 
  end

  def show
    @category = Category.find(params[:id])
  end


  def index
    @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update category_params
      redirect_to Categories_path
    else :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path

  end


  private
  def category_params 
    params.require(:category).permit(:title)
  end










end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="form-group">
  <%= form_for :category, url: categories_path do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/categories/edit.html.erb
<br>
<div class="quiz-form-container">
  <div class="well">
    <h1> Edit a Category </h1>
      <%= render 'form' %>
  </div>
</div>

app/views/categories/index.html.erb
<h1>Show All Categories Page</h1>
<p>views/categories/index.html.erb</p>

<h1>Add a Category</h1>
<%= render "form" %>
<br>
<br>
<br>
<% @categories.each do |c| %>
  <p><%= link_to c.title, category_path(c) %></p>
  <p><%= link_to 'edit', edit_category_path(c), class: "btn btn-xs btn-primary" %>
  <%= link_to 'delete', category_path(c), method: :delete, data:{confirm: "you sure"}, class: "btn btn-xs btn-danger" %></p>
  <hr>
<% end %>

app/views/categories/show.html.erb
<br>
<%= link_to 'Category Index', categories_path %> 
<br>

<center><h1><%= @category.title %></h1></center>
<br> 

<h2><%= @category.title %> Quizzes</h2>
<hr>
  <% @category.quizzes.each do |q| %>
    <h4><%= q.title %></h4>
    <h4><%= q.body %></h4>
    <h4><%= q.level %></h4>
    <hr>
  <% end %>  