config/routes.rb
Rails.application.routes.draw do

  get    'signup'  =>  'users#new'
  get    'login'   =>  'sessions#new'
  post   'login'   =>  'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users

  get 'users/new'
  resources :quizzes do 
    resources :questions
  end 

  resources :questions do
    resources :answers, only: [:create, :update]
  end
  
  resources :categories

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeCore Q</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CodeCore Q</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Categories", categories_path %></li>
            <li><%= link_to "Quizzes", quizzes_path %></li>

            <li class="active"><a href="./">Sign In <span class="sr-only">(current)</span></a></li>
            <% if logged_in? %>
            <li><%= link_to "**SIGN OUT**", logout_path, method: :delete %></li>
            <li class="dropdown">
              <% end %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>

              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li><%= link_to "about", "#" %></li>
                <li class="divider"></li>
                <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <%= flash[:notice] || flash[:error] || flash[:alert] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/newapp.htlm.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeCore Q</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CodeCore Q</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

        <ul class="nav navbar-nav navbar-right"><li><%= link_to "Quizzes", quizzes_path %></li>
            <li class="active"><a href="./">Sign In <span class="sr-only">(current)</span></a></li>

          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li><%= link_to "about", "#" %></li>
                <li class="divider"></li>
                <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
              </ul>
            </li>
            <% else %>
            <% end %>
          </ul>
    </nav>
  </div>
</header>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeCore Q</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'welcome', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CodeCore Q !WELCOME LAYOUT!</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <ul class="nav navbar-nav navbar-right">
            <!-- <li class="active"><%= link_to "Sign In", login_path %><span class="sr-only">(current)</span></li> -->

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Log In<span class="caret"></span></a>
              <ul class="dropdown-menu login-menu" role="menu">
                <li><%= render "sessions/form" %></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <%= yield %>
  </body>
</html>